jasper-db:
  # For transparency sake: github.com/sylnsr/docker-postgres-ssl
  # Uses the official Postgres image with SSL
  image: sylnsr/postgres-ssl:9.4
  environment:
      - POSTGRES_USER=jasperapp
      - POSTGRES_PASSWORD=jasperapp
    ports:
      - ":5432"

jasper-server:
  build: .
  command: development
  ports:
    - :8080
  links:
    - jasper-db:db
  environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=jasperapp
    - DB_USERNAME=jasperapp
    - DB_PASSWORD=jasperapp
    - WAIT_FOR_DB=1